pp_user_register:
    path:     /profile/register
    defaults: { _controller: PPUserBundle:Registration:myRegister}

pp_user_search:
    path:     /users
    defaults: { _controller: PPUserBundle:ShowUser:searchResult}
    
pp_user_profile:
    path:     /{slug}
    defaults: { _controller: PPUserBundle:ShowUser:index}
    requirements:
        page: \d+

pp_user_edit:
    path:     /profile/edit
    defaults: { _controller: PPUserBundle:ShowUser:edit}

pp_user_gallery:
    path:     /{slug}/gallery
    defaults: { _controller: PPUserBundle:ShowUser:gallery}