pp_user_register:
    path:     /profile/register
    defaults: { _controller: PPUserBundle:Registration:myRegister}

pp_user_search:
    path:     /users
    defaults: { _controller: PPUserBundle:ShowUser:searchResult}
    
pp_user_profile:
    path:     /{slug}
    defaults: { _controller: PPUserBundle:ShowUser:index}
    requirements:
        page: \d+

pp_user_edit:
    path:     /profile/edit
    defaults: { _controller: PPUserBundle:ShowUser:edit}

pp_user_gallery:
    path:     /{slug}/gallery
    defaults: { _controller: PPUserBundle:ShowUser:gallery}
    
pp_user_setting:
    path:     /{slug}/settings
    defaults: { _controller: PPUserBundle:Setting:index}
 
pp_user_disable_account:
    path:     /settings/disable
    defaults: { _controller: PPUserBundle:Setting:disableAccount}

pp_user_resetting_request:
    path: /security/request
    defaults: { _controller: PPUserBundle:Resetting:myRequest}        

pp_user_resetting_send_email:
    path: /security/send-email
    defaults: { _controller: PPUserBundle:Resetting:mySendEmail} 

pp_user_resetting_check_email:
    path: /security/check-email
    defaults: { _controller: PPUserBundle:Resetting:myCheckEmail}     

pp_user_resetting_reset:
    path: /security/reset/{token}
    defaults: { _controller: PPUserBundle:Resetting:reset} 
