page_help:
    path:     /help
    defaults: { _controller: PPPageBundle:Page:help }

page_about:
    path:     /about/
    defaults: { _controller: PPPageBundle:Page:about }
    
page_terms:
    path:     /policies/terms/
    defaults: { _controller: PPPageBundle:Page:terms }
    
page_cookies:
    path:     /policies/cookies/
    defaults: { _controller: PPPageBundle:Page:cookies }

page_privacy:
    path:     /policies/privacy/
    defaults: { _controller: PPPageBundle:Page:privacy }
    
page_license:
    path:     /policies/license/
    defaults: { _controller: PPPageBundle:Page:license }


 